version: "3"

services:
  anuma_explorer:
    container_name: anuma_explorer
    image: anuma/anuma-explorer:latest
    restart: unless-stopped
    environment:
      API_URI: "http://localhost:8000"
      API_WS_URI: "ws://localhost:8000"
    ports:
      - "8080:8080/tcp"

  anuma_rest_server:
    container_name: anuma_rest_server
    image: anuma/anuma-rest-server:latest
    restart: unless-stopped
    environment:
      ANUMAD_HOST_1: anumad:12512
      SQL_URI: postgresql+asyncpg://postgres:postgres@postgresql:5432/postgres
    ports:
      - "8000:8000/tcp"
    links:
      - anumad
      - postgresql

  anuma_db_filler:
    container_name: anuma_db_filler
    image: anuma/anuma-db-filler:latest
    restart: unless-stopped
    environment:
      DEBUG: "true"
      ANUMAD_HOST_1: anumad:12512
      SQL_URI: postgresql://postgres:postgres@postgresql:5432/postgres
    links:
      - anumad
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432/tcp"
    volumes:
      - postgresql:/var/lib/postgresql/data/

  anumad:
    container_name: anumad
    image: AnumaNetwork/anumad:latest
    restart: unless-stopped
    ports:
      - "12512:12512/tcp"
      - "12513:12513/tcp"
    volumes:
      - anumad:/app/data/
    command: anumad --utxoindex --connect=kdxweb.anumacalc.net

volumes:
  postgresql:
  anumad:
